### ISSUE TITLE
Still requires `GITHUB_TOKEN` if `create_release` is false

### ISSUE THREAD

**Issue by ndarilek** [firebelley/godot-export#12]
Thanks for this action!

I'm trying to export without creating a release. If I set `create_release: false` and leave out the token, I get:

```
2020-04-15T21:18:20.7351972Z with:
2020-04-15T21:18:20.7352134Z   godot_executable_download_url: https://archive.hugo.pro/godot-tuxfamily/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
2020-04-15T21:18:20.7352420Z   godot_export_templates_download_url: https://archive.hugo.pro/godot-tuxfamily/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
2020-04-15T21:18:20.7352561Z   godot_template_version: 3.2.1.stable
2020-04-15T21:18:20.7352668Z   relative_project_path: ./
2020-04-15T21:18:20.7352772Z   create_release: false
2020-04-15T21:18:20.7352858Z   base_version: 0.0.1
2020-04-15T21:18:20.7352960Z ##[endgroup]
2020-04-15T21:18:20.8165992Z /home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:7854
2020-04-15T21:18:20.8166707Z             throw new Error('Parameter token or opts.auth is required');
2020-04-15T21:18:20.8167130Z             ^
2020-04-15T21:18:20.8167205Z 
2020-04-15T21:18:20.8167410Z Error: Parameter token or opts.auth is required
2020-04-15T21:18:20.8168066Z     at Function.getAuthString (/home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:7854:19)
2020-04-15T21:18:20.8168403Z     at Function.getOctokitOptions (/home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:7819:29)
2020-04-15T21:18:20.8168699Z     at new GitHub (/home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:7803:22)
2020-04-15T21:18:20.8169082Z     at Module.560 (/home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:10579:22)
2020-04-15T21:18:20.8169341Z     at __webpack_require__ (/home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:22:30)
2020-04-15T21:18:20.8169574Z     at startup (/home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:37:19)
2020-04-15T21:18:20.8169816Z     at /home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:43:18
2020-04-15T21:18:20.8170072Z     at Object.<anonymous> (/home/runner/work/_actions/firebelley/godot-export/v1.2.0/dist/index.js:46:10)
2020-04-15T21:18:20.8170168Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-04-15T21:18:20.8170262Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

Thanks, please let me know if you need any additional details.

**Comment by firebelley** [comment]
Thank you for the report! This is now fixed in the latest version https://github.com/firebelley/godot-export/releases/tag/v1.3.0

Please don't hesitate to open more issues with your bugs and requests!

**Comment by ndarilek** [comment]
Awesome, thanks so much for the quick fix!
